# Generated by Django 4.2.4 on 2023-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_direccion_order_email_order_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(default='Sin direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
