# Generated by Django 4.2.4 on 2023-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_direccion_alter_order_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
