# Generated by Django 4.2.4 on 2023-08-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
