# Generated by Django 4.2.4 on 2023-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_precio_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(default='En Sucursal', max_length=100),
        ),
    ]
